# Generated by Django 2.2.7 on 2019-11-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=125)),
                ('todo_creation_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='todoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item_text', models.CharField(max_length=150)),
                ('todo_item_status', models.BooleanField(default=False)),
                ('todo_item_duedate', models.DateTimeField(auto_now=True, null=True)),
                ('todo_item_completion', models.DateTimeField(auto_now=True, null=True)),
                ('todo_item_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoMain')),
            ],
        ),
    ]
