# Generated by Django 2.2.7 on 2019-11-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_item_main',
            new_name='todo_item_from',
        ),
    ]
