# Generated by Django 2.2.7 on 2019-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191129_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_item_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_item_duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
