# Generated by Django 2.2.7 on 2019-11-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191129_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomain',
            name='todo_status',
            field=models.BooleanField(default=False),
        ),
    ]
